[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173

# Environment variables for Netlify builds
[template.environment]
  VITE_FIREBASE_API_KEY = "Your Firebase API Key"
  VITE_FIREBASE_AUTH_DOMAIN = "Your Firebase Auth Domain"
  VITE_FIREBASE_PROJECT_ID = "Your Firebase Project ID"
  VITE_FIREBASE_STORAGE_BUCKET = "Your Firebase Storage Bucket"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "Your Firebase Messaging Sender ID"
  VITE_FIREBASE_APP_ID = "Your Firebase App ID"